EXTERNAL_A_CHANNEL_0 = 0
DAC_C_OUT = 1
CURRENT_METER_ID = 2
VOLTAGE_METER_ID = 3
UP_DOWN_RES_CTRL_ID = 4
LOADER_CTRL_ID = 5
FREQ_MEASURE_ID = 6
EXTERNAL_A_CHANNEL_1 = 7
EXTERNAL_A_CHANNEL_2 = 8

MAX_CHANNEL_NUM = 37